#!/usr/bin/env python3
"""Regenerate js/symbols.js from symbols/*.dop so the app works from file://."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
sets = {}
for f in sorted((root / 'symbols').glob('*.dop')):
    sets[f.name] = f.read_text()
groups = {
    'Atari 8-bit': ['hardware.dop', 'sys.dop'],
    'Atari XL/XE OS': ['atarixl.dop'],
    'Atari floating point, BASIC, DOS': ['atarifp.dop', 'basic.dop', 'dos.dop'],
    'Commodore 64': ['6510.dop', 'vic.dop', 'sid.dop', 'cia.dop'],
    'BBC Micro': ['bbcmos.dop', 'bbchw.dop'],
    'BBC Micro MOS buffers': ['bbcmosbuf.dop'],
}
# Priority when several sets name the same thing: earlier wins. atarixl.dop
# comes before sys.dop so XL/XE addresses replace 400/800 ones.
order = ['atarixl.dop', 'hardware.dop', 'sys.dop', 'atarifp.dop', 'basic.dop', 'dos.dop',
         '6510.dop', 'vic.dop', 'sid.dop', 'cia.dop', 'bbcmos.dop', 'bbchw.dop', 'bbcmosbuf.dop']
out = root / 'js' / 'symbols.js'
out.write_text(
    '/* Generated by tools/embed-symbols.py from symbols/*.dop. Do not edit. */\n'
    'window.XDisSymbols = ' + json.dumps({'groups': groups, 'order': order, 'files': sets}, indent=1) + ';\n')
print('wrote', out, len(sets), 'sets')
