#!/usr/bin/env python3
"""Regenerate js/symbols.js from symbols/*.dop so the app works from file://."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
sets = {}
for f in sorted((root / 'symbols').glob('*.dop')):
    sets[f.name] = f.read_text()
groups = {
    'Atari 8-bit': ['hardware.dop', 'sys.dop'],
    'Commodore 64': ['6510.dop', 'vic.dop', 'sid.dop', 'cia.dop'],
}
out = root / 'js' / 'symbols.js'
out.write_text(
    '/* Generated by tools/embed-symbols.py from symbols/*.dop. Do not edit. */\n'
    'window.XDisSymbols = ' + json.dumps({'groups': groups, 'files': sets}, indent=1) + ';\n')
print('wrote', out, len(sets), 'sets')
