#!/usr/bin/env python3
"""Generate the VBXE symbol sets.

    tools/make-vbxe.py

Writes symbols/vbxe.dop (registers at $D640) and symbols/vbxe7.dop ($D740:
the board can be decoded at either, depending on how it is installed), then
run tools/embed-symbols.py.

Source: "VideoBoard XE FX Core version 1.26 Programmer's Manual" by
T. Piorek (2013), chapter CORE REGISTERS (FX CORE). Register names are the
manual's. Where an address means one thing when written and another when
read, the read name is an ";xdis read" line, used by instructions that read
the address. GTIA emu cores have only CORE_VERSION, MINOR_REVISION, CSEL and
CR/CG/CB, at the same addresses.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# offset from $Dx40: (write name, description, read name, description)
REGISTERS = [
    (0x00, 'VIDEO_CONTROL', 'xdl_enabled, xcolor, no_trans, trans15',
     'CORE_VERSION', 'core type: $10 FX, $11 GTIA emu'),
    (0x01, 'XDL_ADR0', 'XDL address in VRAM, bits 0-7',
     'MINOR_REVISION', 'bit 7: RAMBO core; bits 6-0: BCD revision ($26 = v1.26)'),
    (0x02, 'XDL_ADR1', 'XDL address in VRAM, bits 8-15', None, None),
    (0x03, 'XDL_ADR2', 'XDL address in VRAM, bits 16-18', None, None),
    (0x04, 'CSEL', 'palette: colour number to change (CB write increments it)', None, None),
    (0x05, 'PSEL', 'palette: palette number to change', None, None),
    (0x06, 'CR', 'palette: red component (bits 7-1)', None, None),
    (0x07, 'CG', 'palette: green component (bits 7-1)', None, None),
    (0x08, 'CB', 'palette: blue component (bits 7-1); increments CSEL', None, None),
    (0x09, 'COLMASK', 'AND mask for overlay/playfield collision detection', None, None),
    (0x0A, 'COLCLR', 'any write clears COLDETECT',
     'COLDETECT', 'overlay/playfield collisions detected'),
    (0x10, 'BL_ADR0', 'BlitterList address in VRAM, bits 0-7',
     'BLT_COLLISION_CODE', 'collision code of the last blit (0: none)'),
    (0x11, 'BL_ADR1', 'BlitterList address in VRAM, bits 8-15', None, None),
    (0x12, 'BL_ADR2', 'BlitterList address in VRAM, bits 16-18', None, None),
    (0x13, 'BLITTER_START', 'bit 0: 1 starts the blitter, 0 stops it',
     'BLITTER_BUSY', 'non-zero while the blitter runs (bit 1 BUSY, bit 0 BCB_LOAD)'),
    (0x14, 'IRQ_CONTROL', 'bit 0: blitter-done IRQ enable; a write acknowledges',
     'IRQ_STATUS', 'bit 0: blitter-done IRQ requested'),
    (0x15, 'P0', 'overlay/playfield priority for attribute map cells (P0)', None, None),
    (0x16, 'P1', 'overlay/playfield priority for attribute map cells (P1)', None, None),
    (0x17, 'P2', 'overlay/playfield priority for attribute map cells (P2)', None, None),
    (0x18, 'P3', 'overlay/playfield priority for attribute map cells (P3)', None, None),
    (0x1D, 'MEMAC_B_CONTROL', 'MEMAC-B: bit 7 CPU, bit 6 ANTIC enable, bits 4-0 16K bank at $4000', None, None),
    (0x1E, 'MEMAC_CONTROL', 'MEMAC-A: bits 7-4 base page/16, bit 3 CPU, bit 2 ANTIC enable, bits 1-0 size', None, None),
    (0x1F, 'MEMAC_BANK_SEL', 'MEMAC-A: bit 7 global enable, bits 6-0 VRAM bank', None, None),
]


def dop(base):
    lines = [f'; VBXE (VideoBoard XE) FX core 1.26 registers at ${base:04X}',
             '; Generated by tools/make-vbxe.py from the FX Core 1.26 Programmer\'s Manual',
             '; (T. Piorek). Names used when instructions read an address that means',
             '; something else when written are ;xdis read lines.', '',
             ';       FX CORE REGISTERS', '']
    for off, wname, wdesc, rname, rdesc in REGISTERS:
        a = base + off
        lines.append(f'data {wname}=${a:04X}'.ljust(44) + f';{wdesc}')
        if rname:
            lines.append(f';xdis read {rname}=${a:04X}'.ljust(44) + f'; {rdesc}')
    return '\n'.join(lines) + '\n'


def main():
    for name, base in (('vbxe.dop', 0xD640), ('vbxe7.dop', 0xD740)):
        (ROOT / 'symbols' / name).write_text(dop(base))
        print('wrote symbols/' + name)


if __name__ == '__main__':
    main()
